# Generated by Django 3.2.7 on 2023-03-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('one', 'Male'), ('two', 'Female')], max_length=100)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
                ('SchoolLevel', models.CharField(choices=[('one', '8 Complete'), ('two', '10 Complete'), ('three', '12 Complete'), ('four', 'Diploma'), ('five', 'Degree'), ('six', 'Vocational school')], max_length=100)),
                ('priorProgrammingBackground', models.BooleanField(default=False, null=True)),
                ('currentOccupation', models.CharField(max_length=100)),
                ('convinientTime', models.CharField(max_length=100)),
                ('ReasonForAttendance', models.TextField(null=True)),
                ('howDidYouHearAboutUs', models.CharField(max_length=100, null=True)),
                ('isSelected', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
